[package]
name = "manga-tui"
version = "0.4.0"
edition = "2021"
authors = ["Josue <josuebarretogit@gmail.com>"]
readme = "README.md"
homepage = "https://github.com/josueBarretogit/manga-tui"
repository = "https://github.com/josueBarretogit/manga-tui"
description = "Read manga in your terminal"
keywords = ["cli", "command-line"]
categories = ["command-line-interface"]
license = "MIT"
exclude = [
  "public/*",
  "data_test/*"
]

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets", "palette", "unstable-widget-ref"] }
ratatui-image = {  version = "1.0.5", features = ["rustix"]}
throbber-widgets-tui = "0.8.0"
tui-input = "0.11.0"
tui-widget-list = "0.13.0"
crossterm = { version = "0.28.1", features = ["event-stream"] }
directories = "5.0.1"
image = "0.25.1"
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0.210", features = ["derive"] }
strum = "0.26.3"
strum_macros = "0.26"
color-eyre = "0.6.2"
futures = "0.3.28"
bytes = { version = "1", features = ["serde"] }
serde_json = "1.0.117"
once_cell = "1.19.0"
chrono = "0.4.38"
open = "5"
rusqlite = { version = "0.31.0", features = ["bundled"] }
clap = { version = "4.5.18", features = ["derive", "cargo"] }
zip = "2.1.6"
toml = "0.8.19"
epub-builder = "0.7.4"

[dev-dependencies]
httpmock = "0.7.0-rc.1"
pretty_assertions = "1.4.0"
rusty-hook = "0.11.2"
uuid = { version = "1.10.0", features = ["v4", "fast-rng"] }
fake = "2.10.0"
http = "1.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59.0", features = ["Win32_Foundation", "Win32_System_Console", "Win32_UI_HiDpi"]}

