# The format of the manga downloaded 
# values : cbz , raw, epub 
# default : cbz 
download_type = "cbz" 
 
# Download image quality, low quality means images are compressed and is recommended for slow internet connections 
# values : low, high 
# default : low 
image_quality = "low" 
